#+TITLE: A Geometric Approach to Fluid Flows in Pipes
#+AUTHOR: Paul Bryan
#+SETUPFILE: ~/.emacs.d/org-templates/bibliography.org
#+OPTIONS: toc:nil

# ***  Class
#+LATEX_CLASS: amsart

# *** Macros
#+LATEX_HEADER: \input{local_definitions}

# *** For bundling
#+LATEX_HEADER: \usepackage{snapshot}

# **** Other LaTeX Packages
#+LATEX_HEADER: \usepackage{mathtools}

# *** Author
#+LATEX_HEADER: \address{Department of Mathematics, University of California San Diego}
#+LATEX_HEADER: \email{pbryan@ucsd.edu}

# *** Metadata
#+LaTeX_HEADER: \keywords{Pipe flows, Navier-Stokes, Fluid Mechanics, Continuum Mechanics, Riemannian Geometry}
#+LATEX_HEADER: \subjclass[2010]{}

# *** Other formatting settings
#+LATEX_HEADER: \date{}

\begin{abstract}
A geometric approach to fluid flows in pipes.
\end{abstract}

* Notes								   :noexport:
** Refs
- Free boundary problems: Problems on Time-Varying Domains: Formulation, Dynamics, and Challenges. E. Knobloch, R. Krechetnikov.
** Background
This describes a geometric approach broadening the technique described in \cite{MR2384375}.
** Lie Derivative
\begin{lemma}
Let $f : M \to \RR$ be a smooth, positive function, $X$ a vector field and $\measure$ a volume form.  Then
\[
\div_{f\mu} (X) f\mu = \div_{\mu} (f X)\mu
\]
or equivalently
\[
\lie_X (f\mu) = \lie_{fX} \mu.
\]
\end{lemma}

\begin{proof}
We have
\[
\lie_X (f\mu) = (\lie_X f) \mu + f\lie_X\mu,
\]
whilst
\[
\begin{split}
\lie_{fX} \mu &= df\wedge \iota_X \mu + f\lie_X \mu \\
&= \iota_X df\wedge \mu + f\lie_X \mu \\
&= (\lie_X f) \mu + f\lie_X \mu.
\end{split}
\]
where the second line follows from the fact that $\iota_X$ is an anti-derivation and $\mu$ is an $n$-form so that $df \wedge \mu$ is an $n+1$ form and hence equal to zero.  This gives
\[
\iota_X 0 = \iota_X (df\wedge \mu) = \iota_X df \wedge \mu - df \wedge \iota_X \mu.
\]
\end{proof}

** Conservation of energy
Need to describe how our ``moving'' domain is defined?  Perhaps everything follows from conservation of energy? It would be nice to get conservation of momentum from a scalar conservation principle.

** Derivation of Euler's eqn. and Navier Stokes
Let us just briefly recall the derivation of these equations and establish some notation in the process. Following a particle at \(x \in \Omega(0)\), we get a smooth map \(\phi : \Omega(0) \times [0, T) \to \RR^3\). The point \(\phi(x, t) \in \Omega(t)\) is the position at time \(t\) of the particle starting at \(x\) at time \(t=0\). Let us use the notation \(\phi_t(x) = \phi(x, t)\). We then of course have the relation \(\phi_0 (x) = x\) for every \(x \in \Omega\).

Conservation of mass says that the mass density is constant along the flow. That is,
\[
\density_t (\phi_t(x)) dx = \density_0 (x) dx.
\]
Pulling back to \(Omega(0)\) by \(\phi_t\) this says
\[
\density_t (x) \measure_t = \pullback{\phi_t} \left(\density_t (\phi_t(x)) dx\right) = \pullback{\phi_0} \left(\density_0 (x) dx\right) = \density_0(x) \measure_0.
\]
* Introduction
- Argument works for arbitrary embedded pipes.
- No boundary matching in discretisation.
- Take in the spirit of Hughes and Lubliner: We show the ideas work more generally in much the same way as before.
- No need to mess around with Jacobians.
- Non-orthogonal cross-sections also: moving water from one resovior to another, we probably only care about the flow in the direction parallel to the earth and so orghotongal to gravity. Give some pictures.
* Notation and Preliminaries

Recall that the basic equations of continuum mechanics are the conservation of mass and balance of momentum. More fundamental perhaps, is the balance of energy though we will focus primarily on mass and momentum here.  The basic quantities of interest describing the continuum are

- $\density$ - the density of matter,
- $\vec{\velocity}$ - the velocity vector field,
- $\energydensity_{\kinetic} = \frac{1}{2} \|\vec{\velocity}\|^2$ - the kinetic energy density,
- $\energydensity_{\internal}$ - the internal energy density,
- $\energydensity = \energydensity_{\kinetic}  + \energydensity_{\internal}$ - the total energy density,
- $\cauchystress$ - the Cauchy stress tensor, a symmetric $(0,2)$-tensor,
- $\vec{\bodyforce}$ - the external or ``body'' forces.

** The Euclidean Setting

The differential equations expressing the conservation of mass, and balance of momentum are
\begin{align}
\label{eq:euler}
\pd[\density]{t} + \div(\density\vec{\velocity}) &= 0 & & \text{Conservation of Mass} \\
\label{eq:navierstokes}
\pd{t} \left(\density\vec{\velocity}\right) + \div\left(\vec{\velocity} \tensor \density\vec{\velocity}\right) &= \div \cauchystress + \vec{\bodyforce} & & \text{Balance of Momentum} 
\end{align}

These equations may be thought of as the infinitessimal versions of the integral laws which for any family of open subset $\Omega(t)\subset \RR^3$ with smooth boundary, moving with the flow are given by
\begin{align*}
\pd{t} \int_{\Omega} \density &= 0 & & \text{Conservation of Mass} \\
\pd{t} \int_{\Omega} \density\vec{\velocity} &= \int_{\bdry{\Omega}} \ip{\cauchystress}{\nor} + \int_{\Omega} \vec{\bodyforce} = \int_{\Omega} \div \cauchystress + \int_{\Omega} \vec{\bodyforce} & & \text{Balance of Momentum} 
\end{align*}
Here $\nor$ is a smooth unit normal vector field to $\bdry{\Omega}$ and $\ip{\cauchystress}{\nor}$ is a vector field given by contracting $\cauchystress$ and $\nor$ using the metric in the first $T\RR^3$ position of $\cauchystress \in T\RR^3\tensor T\RR^3$.  Assuming that $\cauchystress$ is symmetric, it makes no difference in which position we contract.  The integrals of vector fields are given by integrating the components of the vector fields with respect to the global coordinate vector fields $\pd{x}, \pd{y}, \pd{z} \in T\RR^3$. It's a little remarkable that this construction yields a geometrically invariant differential balance law. This is because by working with respect to the canonical global frame \(\{\pd{x}, \pd{y}, \pd{z}\}\), the balance laws are invariant under Galilean transformations, and hence in particular invariant under isometries of \(\RR^3\).

** The Riemannian Setting

We are primarily interested in the equations of continuum mechanics constrained to an open embedded submanifold $M \overset{\phi}{\to} \RR^3$ with piecewise smooth boundary.  For instance $M$ could by a pipe or channel, a lake, a closed container, a star or a galaxy.  Often in this situation, the global coordinates are not appropriate for the problem at hand and so we work intrinsically on $M$.  For instance, we might be interested in the flow along the main axis of a pipe.  Let us then apply some Riemannian geometry to adapt this problem to the geometry at hand.  See the appendix for a review of the Riemannian geometry needed.

In the case of an embedding $\phi: M \to \RR^3$, the standard metric $\ip{-}{-}$ on $\RR^3$ induces the \emph{pull-back metric} $\metric$ on $\domain$
\[
\metric = \phi^{\star} \ip{-}{-}
\]

Since the divergence is pull-back invariant, i.e. $\div_{\metric} = \phi^{\star} \div_{\RR^3}$, the differential balance equations ``pull back'' to $M$,
\begin{align*}
\pd{t} \density + \div_{\metric} (\density \vec{\velocity}) &= 0 \\
\pd{t} (\density \vec{\velocity}) + \div_{\metric} (\density\vec{\velocity} \tensor \vec{\velocity}) &= \div_{\metric} \cauchystress + \vec{\bodyforce}
\end{align*}
abusing notation by writing $\density$, $\vec{\velocity}$, $\cauchystress$ and $\vec{\bodyforce}$ for the pull-backs, $\phi^{\star}\density$, $\phi^{\star}\vec{\velocity}$, $\phi^{\star}\cauchystress$ and $\phi^{\star}\vec{\bodyforce}$ respectively.

#+BEGIN_remark
This system of equations makes sense on any Riemannian manifold $(M,\metric)$ not just embedded submanifolds of $\RR^3$. The integral form of the balance law also makes sense, and the equivalence of the differential and integral laws follows the analogous proof on \(M, \metric\) as in \cite{MR960687}. However, the integral law for balance of momentum doesn't make sense since in general there is no way in to integrate vector fields ``component-wise''. Indeed, a global frame is lacking for a general Riemannian manifold \((M, \metric)\), but even if such a frame exists, in general, the resulting differential laws will depend on the choice of frame and hence will not be geometrically invariant.
#+END_remark

* Pipe Domain and Divergence Theorem

In this section, we describe a way to reduce the dimension of the the system of balance equations by averaging over ``cross-sections'' in domains that $M$ that admit a product structure.  More generally, perhaps the same idea will work for regularly foliated manifolds $M$ yeilding equations for the quotient by the leaves, or perhaps for manifolds with metrics invariant under some group of isometries again giving equations on the quotient.

To begin, let us define the domain in which we will work and prove a divergence theorem in this domain.  The divergence theorem will be our main tool in deriving the equations for the $1$-d pipe flow.  We work with embedded pipes and channels in Euclidean space $\RR^3$.  Both domains can be represented as embedded cylinders
\[
\domain = (0,\curvelength) \times \disc \to \RR^3
\]
with $\disc \subset \RR^2$ the open unit disc centred on the origin.  We also write $\clsr{\domain} = (0,\curvelength) \times \clsr{\disc}$ with $\clsr{\disc}$ the closed unit disc.  The boundary of $\domain$ is
\[
\bdry{\domain} = \clsr{\disc} \times \{0\} \union \clsr{\disc} \times \{1\} \union S^1 \times (0,\curvelength).
\]

We make the following assumption on the embedding $\phi$ related to the pull-back metric,
\[
\metric = dx^2 + \metric_{\disc}(x, \discparam)
\]
where $x\in (0,\curvelength)$ is the axial parameter, $\discparam \in \clsr{\disc}$ and $\metric_{\disc}$ is a metric on $\clsr{\disc}$.  Thus the metric in the axial direction is independent of the cross section $\disc \times \{x\}$ and the cross section is orthogonal to the axial direction with respect to the metric $\metric$.  This simply says that the domain can by parametrised by a non-degenerate unit-speed curve $\domainaxis$, $x\mapsto \phi(x, \disccenter)$ (with $\disccenter \in \disc$ the center) of length $\curvelength$ which we parametrise by arc-length so that $\metric_{xx} = 1$, and with cross section $\domainxsec{x} = \phi(x, \disc)$ orthogonal in $\RR^3$ to the curve.  The matrix form of the metric is 
\[
\metric = \begin{pmatrix}
1 & 0 \\
0 & \metric_{\disc}(x)
\end{pmatrix}.
\]

Although we work on the fixed manifold $\disc\times \{x\}$, the cross section $\domainxsec{x}$ in $\RR^3$ may vary with $x$ and this is reflected by the dependence on $x$ of the metric $\metric_{\disc}$.  The ``shape'' of the cross section $\domainxsec{x}$ also need not be circular and this is refelcted by the $\discparam$ dependence of the metric $\metric_{\disc}$.  See figure \ref{fig:domain} for a picture of the domain illustrating the notation and these ideas.

\begin{figure}
\caption{The domain}
\label{fig:domain}
\end{figure}

Ultimately we want to integrate the balance equations over the cross section $D$ to obtain equations for the cross section average density and cross section averaged $x$-momentem.  For this, we will need a divergence theorem coming from the product structure of the domain $(\domain, \metric) = (\domaincurve \times \disc, dx^2 + \metric_D)$.  The tangent bundle of $\domain$ decomposes as
\[
TM \simeq T\domaincurve \oplus T\disc
\]
so for any vector field $\vec{X}$ on $\domain$, we have the decomposition
\[
\vec{X} = \xvec{X} \pd{x} + \discvec{X}
\]
with $\xvec{X}$ a smooth function on $\domaincurve$ and $\discvec{X}$ a family (indexed by $x\in\domaincurve$) of vector fields on $\disc$.  The block structure on the metric implies
\[
\sqrt{\det \metric} = \sqrt{\det \metric_{\disc}},
\]
so that the measure induced by the metric is given locally with $y,z$ coordinates on $\disc$ by
\[
\metricmeasure{\metric} = \sqrt{\det \metric} dx \wedge dy \wedge dz = dx \wedge (\sqrt{\det \metric_{\disc}} dy \wedge dz) = dx \wedge \measure_{\disc}
\]
with $\measure_{\disc}(x)$ the family (indexed by $x\in\domaincurve$) of measures induced by the family of metrics $\metric_{\disc}(x)$.

Let us write 
\[
\xsecarea (x) = \int_{\disc} \measure_{\disc}(x)
\]
for the cross sectional area of \(D\) measured with the metric \(\metric_{\disc}(x)\), and
\[
\avg{\genfunc}(x) = \frac{1}{\xsecarea(x)} \int_{\disc} f \measure_{\disc} (x)
\]
for the average of $\genfunc: M \to \RR$ over $\disc$ measured with respect to \(\metric_{\disc} (x)\).

Subsets, \(\Omega \subset M\) also inherit a decomposition into \(x\)-slices,
\[
\Omega = \union_{x \in \domaincurve} \Omega(x)
\]
where \(\Omega(x) = \Omega \intersect (\{x\} \times \disc)\). By replacing \(\disc\) with \(\Omega\) above, we also obtain 
\[
\xsecarea_{\Omega} (x) = \int_{\Omega(x)} \measure_{\disc} (x)
\]
and
\[
\avg{\genfunc}_{\Omega} (x) = \frac{1}{\xsecarea_{\Omega} (x)} \int_{\Omega(x)} f \measure_{\disc} (x).
\]
We will restrict our attention to "nice" domains \(\Omega\), meaning that each \(\Omega(x)\) is an open set with smooth enough boundary for Stokes' theorem to apply.

\begin{theorem}[Divergence Theorem]
\label{thm:div_vec}
For any vector field $X = \xvec{X} + \discvec{X}$ we have
\[
\div X \measure_{\disc} = \pd{x} (\xvec{X} \measure_{\disc}) + \div_{\disc} \discvec{X} \measure_{\disc}.
\]
Therefore, given any nice \(\Omega \subset M\), we have
\[
\begin{split}
\int_{\Omega(x)} \div X \measure_{\disc}(x) &= \int_{\Omega(x)} \pd{x} (\xvec{X} \measure_{\disc}) + \int_{\Omega(x)} \div_{\disc} \discvec{X} \measure_{\disc} \\
&= \int_{\Omega(x)} \pd{x} (\xvec{X} \measure_{\disc}) + \int_{\bdry{\Omega(x)}} \ip{\discvec{X}}{\discvec{\nor}} \measure_{\bdry{\disc}}
\end{split}
\]
where $\discvec{\nor}$ is the outer unit normal field to $\bdry{\Omega(x)}$, $\div_{\disc}$ is the divergence with respect to $\metric_{\disc}$ on $\disc$, and $\measure_{\bdry{\disc}}$ the induced ``surface'' measure on $\bdry{\Omega(x)}$.
\end{theorem}

\begin{proof}
In local coordinates, the assumptions on the metric imply the divergence may be written
\[
\begin{split}
\div X &= \frac{1}{\sqrt{\det\metric_{\disc}}} \left[\pd{x} (\sqrt{\det \metric_{\disc}} \xvec{X}) + \pd{y} (\sqrt{\det \metric_{\disc}} \yvec{X}) + \pd{z} (\sqrt{\det \metric_{\disc}} \zvec{X})\right] \\
&= \pd{x} \xvec{X} + \frac{\pd{x} \sqrt{\det \metric_{\disc}}}{\sqrt{\det \metric_{\disc}}} \xvec{X} + \frac{1}{\sqrt{\det\metric_{\disc}}} \left[\pd{y} (\sqrt{\det \metric_{\disc}} \yvec{X}) + \pd{z} (\sqrt{\det \metric_{\disc}} \zvec{X})\right] \\
&= \div_{\domaincurve} \xvec{X} + \frac{\pd{x} \sqrt{\det \metric_{\disc}}}{\sqrt{\det \metric_{\disc}}} \xvec{X} + \div_{\disc} \discvec{X}.
\end{split}.
\]
Note that the divergence doesn't quite inherit a block decomposition from the metric since the metric on $\disc$ varies with $x\in\domaincurve$.  However, by multiplying by $\measure_{\disc} = \sqrt{\det \metric_{\disc}} dy \wedge dz$, we obtain the decomposition
\[
\div X \measure_{\disc} = \pd{x} (\xvec{X} \measure_{\disc}) + \div_{\disc} \discvec{X} \measure_{\disc}
\]
where we make the convention,
\[
\pd{x} (\measure_{\disc}) = \pd{x} \left(\sqrt{\det \metric_{\disc}}\right) dy\wedge dz
\]
Integrating over $\Omega(x)$ gives the first equality in the theorem and applying the ``usual'' divergence theorem gives the second.
\end{proof}

We will also need to differentiate under the integral sign with respect to \(x\). Note that here the cross-sections of the pipe are varying (as expressed by the \(x\)-dependence of \(\measure_{\disc}\)) and the cross-sections of the domain also vary \(\xsec = \xsec(x)\).

\begin{theorem}[Axial Differentiation Under The Integral]
\label{thm:div_vec}
For any function \(f : \Omega \to \RR\) where \(\Omega \subset M\) is a nice domain we have
\[
\begin{split}
\pd{x} \left(\int_{\Omega(x)} f \measure_{\disc}(x)\right) &= \int_{\Omega(x)} \pd[f]{x} \measure_{\disc} + \int_{\Omega(x)} \text{what?} \measure_{\disc} \\
&= \int_{\Omega(x)} \pd[f]{x} \measure_{\disc} + \int_{\Omega(x)} \text{what?} \measure_{\disc}
\end{split}
\]
where $\discvec{\nor}$ is the outer unit normal field to $\bdry{\Omega(x)}$, $\div_{\disc}$ is the divergence with respect to $\metric_{\disc}$ on $\disc$, and $\measure_{\bdry{\disc}}$ the induced ``surface'' measure on $\bdry{\Omega(x)}$.
\end{theorem}

\begin{proof}

\end{proof}

We also need to deal with the term $\div (\density\vec{\velocity} \tensor \vec{\velocity})$ for which we also will derive a divergence theorem.  We break up the proof into a short series of lemmas.  Consider tensors $T\in TM\tensor TM$ and we proceed similarly as for vector fields.  From the decomposition of the tangent bundle, we have the decomposition 
\[
T\domain \tensor T\domain \simeq (T\domaincurve \tensor T\domaincurve) \oplus (T\disc \tensor T\disc) \oplus (T\domaincurve \tensor T\disc)  \oplus (T\disc \tensor T\domaincurve) 
\]
Thus for any tensor $T \in T\domain \tensor T\domain$, we can write
\[
T = T_{xx} \pd{x} \tensor \pd{x} + T_{\disc} + \pd{x} \tensor T_{\disc}^1 + T_{\disc}^2 \tensor \pd{x}
\]
for $T_{xx}$ a smooth function on $\domaincurve$, $T_{\disc} \in T\disc \tensor T\disc$ and $T_{\disc}^i$ $i=1,2$ families (indexed by $x\in\domaincurve$) of vector fields on $\disc$.

The divergence of such tensors also decomposes.  First, let us derive the local expression for the divergence of a tensor $T\in TM\tensor TM$.  There is a degree of ambiguity since the divergence is defined as
\[
\div T = \trace (\conx T)
\]
with $\conx T \in T^{\star}M \tensor TM \tensor TM$ and the trace taken over either the first and second component or the first and third.  In general these traces will give different vector fields $\div T$.  However, if $T$ is symmetric, the trace is unambigous (which can be seen from the local expression obtained below) and we may choose either factor.  We choose the first factor.

The expression for $\div T$ in local coordinates is given by the following lemma:
\begin{lemma}
\label{lem:tensor_div}
Let $T\in TM\tensor TM$ be symmetric. Then
\[
\div T = \left(\div (\iota_{dx^j} T) + \Gamma_{lk}^j T^{kl}\right) \pd{x^j}
\]
where $\iota_{dx^j} T$ is the insertion of $dx^j$ into $T$ on the second factor, given locally as
\[
\iota_{dx^j} \left(T^{kl} \pd{x^k} \tensor \pd{x^l}\right) = T^{kl} \pd{x^l}(dx^j) \pd{x^k} = T^{kj} \pd{x^k}
\]
and divergence on the right hand side is the divergence of the vector field $\iota_{dx^j} T$.
\end{lemma}

\begin{proof}
We compute using the summation convention to sum over repeated indices,
\[
\begin{split}
\div T &= \left(\div T^{ij} \pd{x_i} \tensor \pd{x_j}\right) \\
&= \trace \left(\pd[T^{ij}]{x_k} dx_k \tensor \pd{x_i} \tensor \pd{x_j} + T^{ij} \Gamma_{ik}^l dx_k \tensor \pd{x_l} \tensor \pd{x_j} + T^{ij} \Gamma_{jk}^l dx_k \tensor \pd{x_i} \tensor \pd{x_l} \right) \\
&= \trace \left[\left(\pd[T^{ij}]{x^k} + T^{lj}\Gamma_{lk}^i + T^{il}\Gamma_{lk}^j\right) dx_k \tensor \pd{x_i} \tensor \pd{x_j}\right] \\
&=  \left( \pd[T^{kj}]{x^k} + \Gamma_{lk}^k T^{lj} + \Gamma_{lk}^j T^{kl}\right) \pd{x^j} \\
&= \left( \pd[T^{kj}]{x^k} + T^{kj} \frac{\pd{x^j}\sqrt{\det \metric}}{\sqrt{\det\metric}} + \Gamma_{lk}^j T^{kl}\right) \pd{x^j} \\
&= \left( \frac{1}{\sqrt{\det g}} \pd{x^k}(\sqrt{\det g} T^{kj}) + \Gamma_{lk}^j T^{kl}\right) \pd{x^j} \\
&= \left(\div (\iota_{dx^j} T) + \Gamma_{lk}^j T^{kl}\right) \pd{x^j}.
\end{split}
\]
\end{proof}

In particular, we are interested in the component of $\div T$ tangent to $\domaincurve$, i.e. the $\pd{x}$ component, given by $(\div T)^x = \iota_{dx} \div T$.  

\begin{lemma}
\label{lem:div_insertionx_commute}
For any symmetric tensor field $T\in TM\tensor TM$, $\iota_{dx}$ commutes with $\div$.  That is, we have
\[
\iota_{dx} (\div T) = \div (\iota_{dx} T) = \pd{x} \iota_{dx}^2 T + \frac{\pd{x}\measure_{\disc}}{\measure_{\disc}} \iota_{dx}^2 T + \div_{\disc} (\iota_{dx} T)_{\disc}.
\]
\end{lemma}

\begin{proof}
The second equality is just an application of the divergence theorem \ref{thm:div_vec} to the vector field $\iota_{dx} T$.

For the first equality, let $x_1=x$ and let $x_2,x_3$ be local coordinates on $\disc$.  From lemma \ref{lem:tensor_div} we have
\[
\iota_{dx} \div T = \div \iota_{dx} T + \Gamma_{lk}^x T^{kl}.
\]

To finish, we need to compute $\Gamma_{lk}^x$.  Recall that $\metric_{xk} = \delta_{xk}$ so that
\[
\begin{split}
\Gamma_{lk}^x &= \frac{1}{2} \metric^{xi} \left(\pd{x^l} \metric_{ik} + \pd{x^k} \metric_{li} - \pd{x^i} \metric_{lk}\right) \\
&= \frac{1}{2} \left(\pd{x^l} \delta_{xk} + \pd{x^k} \delta_{lx} - \pd{x} \metric_{lk}\right) \\
&= -\frac{1}{2} \pd{x} \metric_{lk}.
\end{split}
\]
Then we have
\[
\Gamma_{lk}^x T^{kl} = \trace \left(\pd[\metric]{x} \tensor T\right) = \trace \left(\pd[\metric_{\disc}]{x} \tensor T_{\disc}\right)
\]
where the trace here is the total contraction of $\pd[\metric]{x} \in T^{\star}M\tensor T^{\star}M$ with $T \in TM\tensor TM$ given locally by
\[
\begin{split}
\trace \left(\pd[\metric]{x} \tensor T\right) &= \left(\pd[\metric_{kl}]{x} dx^k \tensor dx^l \right) \left(T^{pq}\pd{x^p} \tensor \pd{x^q}\right) \\
&= \pd[\metric_{kl}]{x} T^{pq} dx^k\tensor dx^l \left(\pd{x^p} \tensor \pd{x^q}\right) = \pd[\metric_{kl}]{x} T^{kl}.
\end{split}
\]

Now while $\pd[\metric]{x} \ne 0$, the trace vanishes by metric compatibility of the Levi-Civita connection,
\[
\begin{split}
\trace\left(\pd[\metric]{x} \tensor T\right) & = \left(\pd[\metric]{x}\right) \left(T^{pq}\pd{x^p}, \pd{x^q}\right) \\
&= \pd{x}\left(\metric\left(T^{pq}\pd{x^p}, \pd{x^q}\right)\right) - \metric\left(\conx_{\pd{x}} \left(T^{pq} \pd{x^p}\right), \pd{x^q}\right) \\
& \quad - \metric \left(T^{pq}\pd{x^p}, \conx_{\pd{x}} \pd{x^q}\right) \\
&= \metric\left(\conx_{\pd{x}} T^{pq}\pd{x^p}, \pd{x^q}\right) + \metric \left(T^{pq}\pd{x^p}, \conx_{\pd{x}} \pd{x^q}\right) \\
& \quad - \metric\left(\conx_{\pd{x}} \left(T^{pq} \pd{x^p}\right), \pd{x^q}\right) - \metric \left(T^{pq}\pd{x^p}, \conx_{\pd{x}} \pd{x^q}\right) \\
&= 0
\end{split}
\]
\end{proof}

We can now give a divergence theorem for the $\pd{x}$-component of symmetric tensor fields $T\in TM\tensor TM$.

\begin{theorem}[Divergence Theorem For 2-Tensors]
\label{thm:div_2tensor}
Let $T$ be a symmetric tensor field $T\in TM\tensor TM$ and \(\Omega \subset M\) on open set with boundary smooth enough for Stokes' theorem to apply.  Then
\[
\begin{split}
\int_{\Omega(x)} (\iota_{dx} \div T) \measure_{\disc} &= \pd{x} (\xsecarea_{\Omega(x)} \avg{\iota_{dx}^2 T}) + \int_{\Omega(x)} \div_{\disc} (\iota_{dx} T)_{\disc} \measure_{\disc}  \\
&= \pd{x} (\xsecarea_{\Omega(x)} \avg{\iota_{dx}^2 T}) + \int_{\bdry{\Omega(x)}} \ip{(\iota_{dx} T)_{\disc}}{\nor} \measure_{\disc}. \\
\end{split}
\]
\end{theorem}

\begin{proof}
This is just an application of lemma \ref{lem:div_insertionx_commute} and the divergence theorem \ref{thm:div_vec} applied to the vector field $\iota_{dx} T$.
\end{proof}

* Bodies in Pipes

** Fluids in Pipes

Now that we have our manifold $M = (0, \curvelength) \times \disc$ and the pull back metric $\metric$ with the product structure described above, we can forget about the actual embedding $\phi$ and work intrinsically on $M$.  A /continuum/ or /body/ is a smooth time dependent family of connected, open submanifolds $\body(t) \subset \domain$ with piecewise smooth boundary $\bdry{\body(t)}$ for $t\in\interval$. We can realise \(\body(t)\) via a map,
\[
\phi: \body \times \interval \to M
\]
smooth on the interior of \(\body\), where \(\body\) is a fixed manifold and each \(\phi_t = \phi(\cdot, t): \body \to M\) is a smooth embedding on the interior of \(B\). Via \(\phi_t\) we may identify \(B\) equipped with the pull-back metric \(\pullback{\phi_t} \metric\) and \(B(t)\) equipped with the metric \(\metric\). Typically we will take \(\body = \body(0)\) and \(\phi_t\) follows the path of a particle along the flow.

The continuum inherits the decomposition
\[
\body(t) = \union_{x\in \domaincurve} \xsec(x, t)
\]
from $\domain$ with 
\[
\xsec(x,t) = \body(t) \intersect \left(\{x\} \times \disc\right)
\]
possibly empty for some values \(x\in\domaincurve\).  Since $\body(t)$ is connected, let
\begin{align*}
x_{\min}(t) &= \inf_{x\in (0,\curvelength)} \Omega(x,t) \ne \emptyset \\
x_{\max}(t) &= \sup_{x\in (0,\curvelength)} \Omega(x,t) \ne \emptyset .
\end{align*}

Thus we have $\xsec(x,t) \ne \emptyset$ precisely for $x \in [x_{\min}, x_{\max}]$.

The boundary $\bdry{\body(t)}$ decomposes as
\[
\bdry{\body(t)} = \xsec(x_{\min}(t), t) \union \xsec(x_{\max}(t), t) \union \relbdry[\body(t)]{M}
\]
with $\relbdry[\body(t)]{M} = \bdry{\body(t)} \intersect \left( \domaincurve \times \clsr{\disc}\right)$.  Note that either one or both of $\xsec(x_{\min(t)}, t)$ or $\xsec(x_{\max(t)}, t) \subset \disc$ may well be equal to just a single point.

We also decompose $\relbdry[\body(t)]{M}$ as
\[
\relbdry[\body(t)]{M} = \bdry{\body}_{\fs}(t) \cup \bdry{\body}_{\is}(t)
\]
with $\bdry{\body}_{\is}(t) = \relbdry[\body(t)]{M} \intersect \bdry{\domain}$, the impermeable surface and $\bdry{\body}_{\fs}(t) \subset \domain$ it's complement, the free surface. The impermeable surface is the part of \(\body(t)\) along the boundary of the domain \(M\), while the free surface lies in the interior of the domain \(M\).

** Balance Laws

We assume that $\body(t)$ comes equipped with a density $\density_t: \body(t) \to \RR$. Working on the fixed parameter space, \(\body \times \interval\) we define the smooth (on the interior of \(\body\)) function
\[
\density ((x, \discparam), t) = \density (\phi_t(x, \discparam))
\]
for \((x,\discparam) \in M\). 

The velocity at time \(t \in \interval\) is a vector field $\vec{\velocity}_t$ on $\body(t)$. Equivalently, via \(\phi_t\) \(\vec{\velocity}_t\) is a one-parameter family of vector fields on \(\body\). Recall that $\density$ and $\vec{\velocity}$ together satisfy the system of equations,
\begin{align*}
\pd{t} \density + \div_{\metric} (\density \vec{\velocity}) &= 0 \\
\pd{t} (\density \vec{\velocity}) + \div_{\metric} (\density\vec{\velocity} \tensor \vec{\velocity}) &= \div_{\metric} \cauchystress + \vec{\bodyforce}.
\end{align*}

** Boundary conditions

We must also specify boundary conditions.  On $\xsec(0, t)$ and $\xsec(\curvelength, t)$, the boundary conditions must be specified,
#+BEGIN_LATEX
\[
\begin{cases}
\density(0, \discparam, t) &= \density_0(\discparam, t) \\
\density(\curvelength, \discparam, t) &= \density_{\curvelength}(\discparam, t) \\
\vec{\velocity}(0, \discparam, t) &= \vec{\velocity}_0(\discparam, t) \\
\vec{\velocity}(\curvelength, \discparam, t) &= \vec{\velocity}_{\curvelength}(\discparam, t)
\end{cases}
\]
#+END_LATEX
for given functions $\density_i : \Omega(i, t) \to \RR$ and time-dependent vector fields $\vec{\velocity}_i$ on $\Omega(i, t)$ for $i=0,L$.  This just gives the flow in and out of the pipe/channel at the endpoints.  

The remaining boundary is more subtle, being composed of the boundary at the impermeable wall and a free boundary. The entire boundary itself is a surface $\relbdry[\body(t)]{M}$ with a well defined normal velocity $\norvec{\fsvelocity}$ independent of any parametrisation. Changing the parametrisation only effects the tangential component of the boundary velocity and conversely any tangential component gives rise to a reparametrisation. We define the \emph{normal velocity} vector field
\[
\norvec{\velocity} = \metric(\vec{\velocity}, \vec{\nor}) \vec{\nor}.
\]

We will assume that the fluid free surface is advected by the flow, so that $\norvec{\velocity} = \norvec{\fsvelocity}$ along the free surface, and that the fluid cannot pass through the impermeable wall, so that \(\norvec{\velocity} = 0\) along the impermeable wall. Since the surface at the impermeable wall is stationary, we have \(\norvec{\fsvelocity} = 0\) and so the entire boundary condition may be written as the Neumann boundary condition, 
\begin{equation}
\label{eq:neumann}
\norvec{\velocity} = \norvec{\fsvelocity}.
\end{equation}

** Transport Theorem

The last ingredient we require is a formula for differentiating under cross-sectional integrals, a "cross-sectional (Reynold's) Transport Theorem".

We need to be a little careful here. If we were integrating over the entire domain \(B\), we could use \(\pushforward{\phi} \partial_t = \vec{\velocity}\). This would be using the Lagrangian point of view which is the point of view adopted so far. However, here we want to fix \(x \in \domaincurve\) and integrate over the /changing/ cross section \(\xsec(x, t) = \body(t) \intersect \left(\{x\} \times \disc\right)\). Now we have the Eulerian point of view, where we do not follow a point along the flow. The upshot is that we need to parametrize \(\Omega(x,t)\) by a time-dependent family of embeddings \(\psi_t : \Omega \to \disc\), but the velocity vector is not in general equal to \(\discvec{\velocity}\).

\begin{theorem}[Transport Theorem]
\label{thm:transport}
Let $f: \body(0) \times \interval \to \RR$ be a smooth function.  Then
\[
\pd{t} \int_{\xsec(x, t)} f \measure_{\disc} = \int_{\xsec(x, t)} \pd[f]{t} \measure_{\disc} + \int_{\bdry{\xsec(t)}} f \ip{\discvec{\velocity}}{\nor} \areameasure
\]
\end{theorem}

\begin{proof}
Keeping $x \in (0, \curvelength)$ fixed, and assuming that \(\xsec(x, t) \subset (\disc, \metric_{\disc}(x))\) is a family of domains with piecewise-smooth boundary, we can parametrise \(\xsec(x, t)\) by a continuous family (smooth on the interior) of embeddings, \(\psi_t: \xsec \to \disc\) with \(\xsec\) a fixed parameter space. Letting \(\discvec{W}\) denote the velocity vector, we have that along the boundary\(\bdry{\xsec(x, t)}\),
\[
\discvec{W} = \discvec{\fsvelocity} = \discvec{\velocity}.
\]

Then using the properties of the Lie derivative keeping mind that $\discvec{\velocity}$ is a time dependent vector field, we compute
\[
\begin{split}
\pd{t} \int_{\xsec(t)} f \measure_{\disc} &= \int_{\xsec(0)} \pd{t} \psi_t^{\star} (f \measure_{\disc}) \\
&= \int_{\xsec(0)} \psi_t^{\star} \lie_{\discvec{W}} (f \measure_{\disc}) \\
&= \int_{\xsec(0)} \psi_t^{\star} \left(\pd[f]{t} \measure_{\disc} + \lie_{\discvec{W}} (f \measure_{\disc})\right) \\
&= \int_{\xsec(0)} \psi_t^{\star} \left(\pd[f]{t} \measure_{\disc} + \discvec{W}(f) \measure_{\disc} + f \div_{\disc} \discvec{W} \measure_{\disc} \right) \\
&= \int_{\xsec(0)} \psi_t^{\star} \left(\pd[f]{t} \measure_{\disc} + \div_{\disc}(f \discvec{W}) \measure_{\disc}\right) \\
&= \int_{\xsec(t)} \left(\pd[f]{t} + \div_{\disc}(f \discvec{W})\right) \measure_{\disc} \\
&= \int_{\xsec(t)} \pd[f]{t} \measure_{\disc} + \int_{\bdry{\xsec(t)}} f \ip{\discvec{\velocity}}{\nor} \areameasure
\end{split}
\]
where the last line used Stokes' Theorem and the fact that \(\discvec{\fsvelocity} = \discvec{\velocity}\) along the free surface \(\bdry{\xsec(x,t)}_{\fs}\) and that \(\ip{\discvec{\velocity}}{\nor} = 0 \) along \(\bdry{\xsec(x,t)}_{\is}\).
\end{proof}


We can now apply our divergence theorems and the transport theorem to deduce a formula for the cross-section averaged material derivative, which will be of great use to us.

\begin{cor}
\label{cor:xsec_md}
Let $f: \body(t) \to \RR$ be a smooth function.  Then
\[
\begin{split}
\int_{\xsec} \left(\pd[f]{t} + \div(f \vec{\velocity})\right) \measure_{\disc} &= \pd{t} (\xsecarea\avg{f}) + \pd{x} (\xsecarea \avg{f \xvec{\velocity}}) - \int_{\bdry{\xsec}} f \norvec{W} \measure_{\bdry{\xsec}} \\
\intertext{Let $\vec{X}(t)$ be a smooth one-parameter family of vector fields on $\body(t)$.  Then}
\int_{\xsec} \iota_{dx} \left(\pd{t} \vec{X} + \div(\vec{X} \tensor \vec{\velocity}) \right) \measure_{\disc} &= \pd{t} (\xsecarea\avg{\xvec{X}}) + \pd{x} (\xsecarea \avg{\xvec{X} \xvec{\velocity}}) - \int_{\bdry{\xsec}} \xvec{X} \norvec{W} \measure_{\bdry{\xsec}}
\end{split}
\]
\end{cor}

\begin{proof}
For the first equation, by the divergence theorem \ref{thm:div_vec} for vector fields and the transport theorem \ref{thm:transport},
\[
\begin{split}
\int_{\xsec} \left(\pd[f]{t} + \div(f \vec{\velocity})\right) \measure_{\disc} &= \pd{t} (\xsecarea \avg{f}) - \int_{\bdry{\xsec}_{\fs}} \ip{f \discvec{\velocity}}{\nor} \sigma + \int_{\xsec} \pd{x} \left(f \xvec{\velocity}\right) + \div_{\disc} (f\discvec{\velocity}) \measure_{\disc} \\
&= \pd{t} (\xsecarea \avg{f}) + \pd{x} (\xsecarea \avg{f \xvec{\velocity}}) + \int_{\xsec} f\xvec{\velocity} \pd{x} \measure_{\disc} + \int_{\bdry{\xsec}_{\fs}} \ip{f\discvec{\velocity}}{\nor - \nor_{\disc}} \areameasure \\
&= \pd{t} (\xsecarea \avg{f}) + \pd{x} (\xsecarea \avg{f \xvec{\velocity}}) + \cdots
\end{split}
\]
where $\vec{\nor}$ is the unit outer normal to $\bdry{\body}$ and $\nor_{\disc}$ is it's projection onto the cross section $\disc$ which is normal to $\bdry{\xsec}$ but generally not unit length.

The second equation comes first from noting that $x$ and $t$ are commuting variables so that $\iota_{dx} \pd[\vec{X}]{t} = \pd[\iota_{dx}\vec{X}]{t} = \pd[\xvec{X}]{t}$.  Next we have
\[
\iota_{dx} (\vec{X}\tensor \vec{\velocity}) = \xvec{X}\vec{\velocity}
\]
and by lemma \ref{lem:tensor_div},
\[
\iota_{dx} \div \vec{X}\tensor \vec{\velocity} = \div \xvec{X}\vec{\velocity}.
\]
Now apply the first equality to the function $f = \xvec{X}$.  Equivalently, to handle the divergence term, we can apply the divergence theorem \ref{thm:div_2tensor} for $2$-tensors.
\end{proof}

* Cross Section Averaged Equations

#+BEGIN_LATEX
\note{Decide on generality. Just do ideal fluids first! Do I do free surface/pressurised?}
#+END_LATEX

** Conservation of Mass

#+BEGIN_LATEX
\note{Need boundary term $\vec{\relvelocity}$. This comes from $\ip{\vec{\velocity}}{\vec{\nor}} = \norvec{\fsvelocity} - W$ 
so that $\xvec{\velocity}\xvec{\nor} = \norvec{\fsvelocity} - W - \ip{\discvec{\velocity}}{\discvec{\nor}}$.}
#+END_LATEX

Now we apply corollary \ref{cor:xsec_md} of the previous section to the conservation of mass equation \eqref{eq:euler},
\[
\pd[\density]{t} + \div(\density\vec{\velocity}) = 0.
\]
Integrate this over $\disc$ to obtain
#+BEGIN_LATEX
\[
\begin{split}
0 &= \int_{\disc} \pd[\density]{t} + \div(\density\vec{\velocity}) \measure_{\disc} \\
&= \pd{t} (\xsecarea \avg{\density}) + \pd{x} (\xsecarea \avg{\density\xvec{\velocity}}) + \int_{\bdry{\disc}} \density\frac{\xvec{\velocity}\xvec{\nor}}{\abs{\discvec{\nor}}}.
\end{split}
\]
#+END_LATEX
The appropriate boundary conditions now become
\begin{align*}
\avg{\density(0, t)} &= \density_0 (t) \\
\avg{\density(\curvelength, t)} &= \density_{\curvelength} (t) \\
\avg{\density\xvec{\velocity}(0, t)} &= (\density\xvec{\velocity})_0 (t) \\
\avg{\density\xvec{\velocity}(\curvelength, t)} &= (\density\xvec{\velocity})_{\curvelength} (t)
\end{align*}
for non-negative function $\density_0, \density_{\curvelength}$ and arbitrary real valued functions $(\density\xvec{\velocity})_0, (\density\xvec{\velocity})_{\curvelength}$.

** Balance of Momentum


We now have the first of our balance equations for the cross sectional averaged values of the density and the momentum in the $x$ direction.  The second equation comes from the $x$-component of the balance of momentum equation:
\[
\iota_{dx} \pd{t} (\density \vec{\velocity}) + \iota_{dx} \div (\density\vec{\velocity} \tensor \vec{\velocity}) - \iota_{dx} \div \cauchystress = \iota_{dx} \vec{\bodyforce}.
\]
Integrating over $\disc$ and applying corollary \ref{cor:xsec_md} and the $2$-tensor divergence theorem to the $\div\cauchystress$ term we obtain
\[
\pd{t} (\xsecarea \avg{\density \xvec{\velocity}}) + \pd{x} (\xsecarea \avg{\density \xvec{\velocity}^2}) - \pd{x} (\xsecarea \avg{\cauchystress^{xx}}) = \xsecarea \avg{\xvec{\bodyforce}} - \int_{\bdry{\disc}} \frac{\density\xvec{\velocity}^2\xvec{\nor}}{\abs{\discvec{\nor}}} + \int_{\bdry{\disc}} \ip{\cauchystress_{x,\disc}}{\frac{\discvec{\nor}}{\abs{\discvec{\nor}}}} \measure_{\bdry{\disc}}.
\]
We have written the extra terms from the divergence theorem on the right hand side since they are integrals over the boundary and so are speficied by the boundary conditions, thus we may think of them as given source terms.

#+BEGIN_LATEX
\note{Need to give boundary conditions}
#+END_LATEX

** The Cross-Sectional Model

#+BEGIN_LATEX
\note{Probably just do ideal fluids for simplicity. Pressurised, free surface and mixed flows may all be treated here. Obtain final 1d equations}
#+END_LATEX

We have now derived the equations for the cross-section averaged quantites
\begin{align}
\label{eq:xsec_mass}
\pd{t} (\xsecarea \avg{\density}) + \pd{x} (\xsecarea \avg{\density\xvec{\velocity}}) &= 0 \\
\label{eq:xsec_mom}
\pd{t} (\xsecarea \avg{\density \xvec{\velocity}^2}) + \pd{x} \left(\xsecarea \avg{\density \xvec{\velocity}^2} - \xsecarea \avg{\cauchystress^{xx}}\right) &= \xsecarea \avg{\xvec{\bodyforce}} + \text{stress term} + \text{pressure term}
\end{align}
with boundary conditions
\begin{equation}
\label{eq:xsec_bdry}
\begin{split}
\xsecarea\avg{\density}(0) &= \density_0 (t) \\
\xsecarea\avg{\density}(L) &= \density_L (t) \\
\xsecarea\avg{\xvec{\velocity}}(0) &= \velocity_0(t) \\
\xsecarea\avg{\xvec{\velocity}}(L) &= \velocity_L(t).
\end{split}
\end{equation}

These equations are fairly general, and as a consequence are not well-posed at this stage.  For one thing, we have too many unknowns because of the stress tensor $\cauchystress$ which we shall deal with later.  The most serious problem however, is the boundary conditions are for $\xsecarea\avg{\density}$ and $\avg{\xvec{\velocity}}$, but the equations are not equations in these variables.  To deal with this problem, we make the approximations $\avg{\density \xvec{\velocity}} \simeq \avg{\density} \avg{\velocity}$ and $\avg{\density \xvec{\velocity}^2} \simeq \avg{\density} \avg{\velocity}^2$.  Will we consider the validity of such approximations shortly, the main assumption being that the variation of $\density$ and $\xvec{\velocity}$ over $\disc$ is small.

#+BEGIN_LATEX
\note{This seems difficult and closely related to the regularity of Navier Stokes equation}
#+END_LATEX

Given any functions $\genfunc, \genfunca: \disc \to \RR$ we have the decomposition into the average value and variation,
\[
\genfunc = \avg{\genfunc} + \var{\genfunc}
\]
with $\var{\genfunc} = \genfunc - \avg{\genfunc}$.  Obviously we have
\[
\int_{\disc} \var{\genfunc} = 0.
\]
This gives the following
\[
\xsecarea \avg{\genfunc \genfunca} = \int_{\disc} \genfunc \genfunca = \xsecarea \avg{\genfunc} \avg{\genfunca} + \xsecarea \avg{\var{\genfunc} \var{\genfunca}}
\]

We are typically intersted in the situation where the various quantities $\genfunc$ such as $\density$ and $\xvec{\velocity}$ are roughly constant over $\disc$ so that $\var{\genfunc}$ is small.  To make the approximation
\[
\xsecarea \avg{\density\xvec{\velocity}} \simeq \xsecarea\avg{\density} \avg{\xvec{\velocity}}
\]
we need to know that the variation remains small for $t>0$.  We know that
\[
\xsecarea(t, x) = \abs{\xsec}_{\metric} \leq \abs{\disc}_{\metric} = \xsecarea_{\max} (x)
\]
for all $t\geq 0$.  From Cauchy-Schwartz we have
\[
\abs{\int \var{\genfunc} \var{\genfuncb}}^2 \leq \int \abs{\var{\genfunc}} \int \abs{\var{\genfuncb}}
\]
so we need to control $\int \abs{\var{\genfunc}}$ and $\int \abs{\var{\genfuncb}}$.  Thus, we need to compute
\[
\pd{t} \int \abs{\var{\genfunc}}
\]
for $\genfunc = \density, \xvec{\velocity}$.  The transport and divergence theorems give
#+BEGIN_LATEX
\[
\begin{split}
\pd{t} \int_{\disc} \abs{\var{\genfunc}} d\measure_{\disc} &= \int_{\disc} \pd{t} \abs{\var{\genfunc}} d\measure_{\disc} + \int_{\disc} \div_{\disc} (\abs{\var{\genfunc}} \discvec{\velocity}) d\measure_{\disc} \\
&= \int_{\disc} \pd{t} \abs{\var{\genfunc}} d\measure_{\disc} + \int_{\bdry{\disc}} \abs{\var{\genfunc}} \ip{\discvec{\velocity}}{\nor_{\disc}}_{\metric_{\disc}} d\measure_{\bdry{\disc}}
\end{split}
\]
#+END_LATEX

#+BEGIN_LATEX
\note{The second integral should be controlled by something like $\sup \abs{\var\genfunc} \times \pd{t}\xsecarea = 0$?}
#+END_LATEX

Thus making the approximations $\avg{\density \xvec{\velocity}} \simeq \avg{\density} \xvec{\velocity}$ and $\avg{\density \xvec{\velocity}^2} \simeq\avg{\density} \avg{\xvec{\velocity}^2}$, the error terms are controlled by the initial error terms.  

#+BEGIN_LATEX
\note{Probably just do ideal fluids and don't worry about details of Cauchystress, pressure etc.}
#+END_LATEX

Before we can write the final form of our equations, we need to investigate $\cauchystress$ further.  Recall that $\cauchystress$ is a symmetric tensor so that in the decomposition of the tangent bundle, we have $\cauchystress^1_{\disc} = \cauchystress^2_{\disc}$ and $\cauchystress_{\disc}$ is a symmetric $(0,2)$-tensor on $\disc$.  A particularly interesting (and common) case is when $\cauchystress = \potential \metric^{-1}$ in which case $\cauchystress$ is given by the scalar potential $\potential$ so that
\[
\div \cauchystress = \grad \potential.
\]
In this case, since $\metric_{xx} = 1$, $\metric^1_{\disc} = \metric^2_{\disc} = 0$ we obtain
\[
\iota_{dx} \div \cauchystress = \pd{x} \potential + \frac{\pd{x}\measure_{\disc}}{\measure_{\disc}} \potential - \frac{\potential}{2} \left(\trace \left(\pd{x} \metric_{\disc} \tensor \metric_{\disc}\right) \right)
\]

From now on we will suppose that the Cauchy stress tensor is of the form $\potential \metric$, a situation referred to in fluid mechanics as that of an ideal fluid.  Thus we ignore viscous effects.  Moreover, we shall make the assmuption that the potential $\phi = - \pressure$, the pressure which we assume is a function of the density
\[
\pressure = \pressure(\density). 
\]

Finally we consider the approximate equations
\begin{align}
\label{eq:xsec_mass_approx}
\pd{t} (\xsecarea \avg{\density}) + \pd{x} (\xsecarea \avg{\density} \avg{\xvec{\velocity}}) &= 0 \\
\label{eq:xsec_mom_approx}
\pd{t} (\xsecarea \avg{\density} \avg{\xvec{\velocity}}) + \pd{x} \left(\xsecarea \avg{\density} \avg{\xvec{\velocity}}^2 + \xsecarea \avg{\density}\right) &= \xsecarea \avg{\xvec{\bodyforce}} + \text{pressure term}
\end{align}
with boundary conditions
\begin{equation}
\label{eq:xsec_bdry_approx}
\begin{split}
\xsecarea\avg{\density}(0) &= \density_0 (t) \\
\xsecarea\avg{\density}(L) &= \density_L (t) \\
\xsecarea\avg{\xvec{\velocity}}(0) &= \velocity_0(t) \\
\xsecarea\avg{\xvec{\velocity}}(L) &= \velocity_L(t).
\end{split}
\end{equation}

#+BEGIN_LATEX
\note{Discuss radial profiles etc. Focus on density, velocity approximately constant over cross sections}
#+END_LATEX

* Analysis of 1D equations
- hyperbolicity, eigenvalues
- anything else?
* Remarks on Computational Aspects
- no boundary matching needed at each cell
- parametrize pipe once and for all (possibly computationally!) and then subsequent simulations should be quite fast because of no boundary matching required at each cell. Give some pictures of this method and boundary matching methods.
- Computation should now be fairly standard and there are well balanced methods.
- mention mixed flows could be treated.
#+LATEX: \appendix
* Review of Riemannian Geometry
\label{app:reviewriemann}

In this section, we recall some notions from Riemannian geometry.  Unless otherwise stated, $(M,\metric)$ will denoted an aribtrary oriented Riemannian manifold $(M^n, \metric)$ with piecewise smooth boundary $\bdry{M}$ in the sense that $\bdry{M}$ is smooth except for a set of Hausdorff dimension (with respect to the measure induced by the metric $\metric$) at most $n-1$.  This allows for singularities on the boundary such as corners as for example in the case of a square pipe.  The important point is that we may integrate over the boundary and the low Hausdorff dimension of the singular set implies that we need not distinguish between integrals over the entire boundary and integrals over the smooth part of the boundary.  Stokes' theorem still applies to integrals over $M$ in this situation.

First, let us recall the notion of tensor contractions.  

\begin{defn}
The trace $\trace: TM \tensor T^{\star}M \to C^{\infty}(M)$ is defined on indecomposable elements $X \tensor \alpha \in TM \tensor T^{\star}M$ 
\[
\trace (X \tensor \alpha) = (x \mapsto \alpha_x (X_x))
\]
and then extended by bilinearity, where $\alpha_x, X_x$ are the fibres of $\alpha$ and $X$ respectively and $\alpha_x (X_x)$ is the dual pairing of $T^{\star}M$ with $TM$.  
\end{defn}

This map is \emph{natural} with respect to restrictions in that
\[
\trace ((X \tensor \alpha)|_V) = (\trace (X \tensor \alpha))|_V
\]
for $V\subset U\subset M$ open subsets and $X\tensor \alpha \in \Gamma(TM\tensor T^{\star}M, U)$ a local section over $U$.

We also define the tensor contraction of any tensor $T\in T^{p+1}_{q+1} \simeq TM \tensor T^{\star}M \tensor T^p_q$ by taking the tensor product of the maps
\begin{align*}
\trace : TM \tensor T^{\star}M &\to C^{\infty}(M) = T^0_0 M \\
\id : T^p_q &\to T^p_q
\end{align*}
so that
#+BEGIN_LATEX
\[
\begin{split}
\trace^1_1 = \trace \tensor \id : TM \tensor T^{\star}M \tensor T^p_q &\to C^{\infty}(M) \tensor T^p_q \simeq T^p_q \\
X \tensor \alpha \tensor T &\mapsto \trace(X\tensor \alpha) \tensor T = \trace(X\tensor \alpha) T.
\end{split}
\]
#+END_LATEX
For any tensor $T\in T^p_q, p,q\geq 1$ and any $k\leq p, l\leq p$, we can define the trace $\trace^k_l T$ by taking the trace on the $k$'th contravariant position (upper index or $k$'th occurance of $TM$) with the $l$'th covariant position (lower index or $l$'th occurance of $T^{\star}M$).  Of course we may compose as many traces as we like, each time reducing each of the convariant and contravariant degrees by $1$.  In particular, given $T\in T^p_p$ we have the total trace $\trace T \in C^{\infty}(M)$ given by
\[
\trace T = \underbrace{\trace^1_1 \circ \dotsc \circ \trace^1_1}_{p\>\text{times}} T.
\]

Finally, by the non-degeneracy of the metric $\metric$, we have the so called ``musical'' isomorphisms
#+BEGIN_LATEX
\[
\begin{split}
\flat : TM &\to T^{\star}M \\
X &\mapsto (Y \mapsto \metric(X, Y))
\end{split}
\]
#+END_LATEX
and $\sharp = \flat^{-1} : T^{\star}M \to TM$.  Then we may contract \emph{with respect to the metric} any tensor $T\in T^p_q$ with $p+q \geq 2$ by using $\flat, \sharp$ to take $T$ into $T^p_q$ with $p,q\geq 1$ and then taking the trace.  Of course this operation is not unique and we must specify both to which position we apply $\flat$ and $\sharp$ and to which positions we apply the trace.  This will always be made clear in context.

Next, let us various ways to differentiate tensors on manifolds.  First, recall the notion of connection and covariant derivative.

\begin{defn}
A connection on a vector bundle $E \to M$ is a vector bundle derivation
\[
\conx: E \to T^{\star}M \tensor E,
\]
that is, a family of maps $\conx_U$ for each open $U\subset M$ commuting with restrictions
\[
\conx_V s|_V = (\conx_U s)|_V
\]
for each open $V \subset U$ and sections $s: U \to E \in \Gamma(U, E)$.  Each map $\conx_U$ is assumed linear on the fibres $E_x$ or equivalently linear on each local trivialisation of $E$.  To say that $\conx$ is a derivation is to say that for any $f\in C^{\infty}(U), s \in \Gamma(U, E)$ we have
\[
\conx_U (f s) = df \tensor s + f \conx s.
\]
\end{defn}

By the natural isomorphism $C^{\infty}(M) \tensor E \simeq E$, $f \tensor s \mapsto fs$ and writing $\conx f = df$, we can write the derivation property suggestively as a tensor derivation
\[
\conx (f \tensor s) = \conx f \tensor s + f \tensor \conx s.
\]

\begin{defn}
We define the \emph{covariant derivative} of $s$ in the direction $X$ by $\conx_X s = \trace (X \tensor\conx s) \in E$ where $\conx s \in \hom(TM, E)$ by the isomorphism
\[
\begin{split}
T^{\star} M \tensor E &\to \hom(TM, E) \\
\alpha \tensor s & \mapsto (X \mapsto \trace((X\tensor\alpha) s) = \alpha(X) s
\end{split}
\]
for indecomposable elements $\alpha \tensor s$ and extended by linearity to all  and with $\alpha(X)_x = \alpha_x (X_x), x \in M$ the fibrewise dual pairing of $T^{\star}M$ with $TM$.
\end{defn}

The covariant derivative satisfies the following two properties
\begin{align*}
\conx_{fX + gY} s &= f\conx_X s + g\conx_Y s & & \text{Linearity of $X \mapsto \conx_X$} \\
\conx_X fs &= X(f) s + f \conx_x s & & \text{Derivation}.
\end{align*}

By the isomorphism $T^{\star} M \tensor E \simeq \hom(TM, E)$, we may define a connection on $E$ by giving a map $X \to E$ satisying the derivation property.

\begin{prop}
\label{prop:tensorconnection}
A connection $\conx$ on $TM$ uniquely determines a connection of any tensor bundle $T^P_q M$
\[
\conx^p_q: T^P_q M \to T^{\star}M \tensor T^P_q M = T^p_{q+1} M
\]
by the requirements
\begin{align*}
(\conx^0_0)_X f &= df(X) = Xf & & \text{Definition on to $T^0_0 M = C^{\infty}(M)$} \\
(\conx^1_0)_X Y &= \conx_x Y & & \text{Definition on $T^1_0 M$} \\
\conx_X \trace(T) &= \trace (\conx_X T)  & & \text{Commutes with contractions} \\
\conx_X (T \tensor S) &= (\conx_X T) \tensor S + T \tensor (\conx_X S) & & \text{Tensor derivation}
\end{align*}
\end{prop}

\begin{theorem}[Fundamental Theorem of Riemannian Geometry]
Let $(M,\metric)$ be a Riemannian manifold.  Then there exists a unique connection $\conx = \conx(\metric)$ such that for all vector fields $X,Y,Z$,
\begin{align*}
\conx_X \metric (Y, Z) &= \metric(\conx_X Y, Z) + \metric(Y, \conx_X Z) & & \text{Metric compatability} \\
\conx_X Y - \conx_Y X &= [X, Y] & & \text{Torsion free} 
\end{align*}
The connection $\conx$ is referred to as either the Levi-Civita or Riemannian connection.
\end{theorem}

From now on, given a Riemannian manifold $(M,\metric)$, $\conx$ will denote the Levi-Civita connection of the metric $\metric$. 

Another way to differentiate tensors on a manifold is via the Lie derivative.  This depends only on the differentiable structure of $M$ and not the Riemannian structure though the interaction between these two structures leads to many interesting ideas.

\begin{defn}
Let $X, Y$ be vector fields.  The Lie derivative of $Y$ in the direction $X$ is defined be
\[
\lie_X Y = [X, Y],
\]
the Lie bracket of $X$ and $Y$, defined as the commutater of $X$ and $Y$ thought of as derivations $C^{\infty}(M) \to C^{\infty}(M)$.
\end{defn}

Just as with connections, we can extend the Lie derivative to the tensor algebra of $M$ by requiring it to commute with contractions and to be a tensor derivation.

\begin{prop}
There is a unique derivation $T^p_q \to T^p_q$, the Lie derivative, determined by the requirements
\begin{align*}
\lie_X f &= df(X) = Xf & & \text{Definition on $T^0_0 M = C^{\infty}(M)$} \\
\lie_X Y &= [X, Y] & & \text{Definition on $T^1_0 M$} \\
\lie_X \trace(T) &= \trace (\lie_X T)  & & \text{Commutes with contractions} \\
\lie_X (T \tensor S) &= (\lie_X T) \tensor S + T \tensor (\lie_X S) & & \text{Tensor derivation}
\end{align*}
\end{prop}

Note that in contrast with a connection, the assignment $X \mapsto \lie_X T$ for $X$ a vector field, $T\in T^p_q$ a tensor field, does not define a tensor field in $T^p_{q+1}$ since the assignment is not $C^{\infty}(M)$ linear.

There is another way to characterise the Lie derivative that we will make extensive use of; by infinitessimal flows.  Here we see the Lie derivative measures the change in a tensor field as we flow along a vector field.

\begin{prop}
Let $X$ be a vector field, and for $\lambda\in \RR$, $\phi_{\lambda} : M \to M$ the flow of $X$.  Then
\[
\lie_X T = \pd{\lambda}|_{\lambda=0} (\phi_{\lambda}^{\star} T)
\]
where $\phi_{\lambda}^{\star}$ is the pull-back of the diffeomorphism $\phi_{\lambda}$ for each $\lambda$.  Note $\phi_{\lambda}$ may not be defined on all of $\RR$, but is always defined on a neighbourhood of $0$ (which may depend on $x\in M$ also).
\end{prop}

This leads to the useful
\begin{cor}
Let $X$ be a vector field with local flow $\phi_{\lambda}$.  Then for any tensor field $T$,
\[
\pd{\lambda} (\phi_{\lambda}^{\star} T) = \phi_{\lambda}^{\star} (\lie_X T).
\]
\end{cor}

Another usefule property is \emph{naturality} with respect to push forward by diffeomorphism.

\begin{prop}
Let $\phi : M \to N$ be a diffeomorphism and $X$ a vector field on $M$.  Then
\[
\lie_{\phi_{\star}X} \phi_{\star}Y = \phi_{\star} \lie_X Y.
\]
\end{prop}

We may also take the Lie derivative of a one parameter family of tensor fields $T_{\lambda}$ with respect to a one-parameter family of vector fields $X_{\lambda}$.  Let $\phi_{\lambda, \mu}: M \to M$ be the flow of $X_{\lambda}$, i.e. for $x\in M$
\[
\pd[\phi_{\lambda,\mu}]{\lambda} (x) = X_{\lambda} (\phi_{\lambda,\mu}(x)).
\]
We have the following characterisation:
\begin{prop}
Let $X_{\lambda}$ be a one parameter family of vector fields with flow $\phi_{\lambda,\mu}$ and $T_{\lambda}$ a one-parameter family of tensor fields on $M$.  Then
\[
\pd{\lambda} \phi_{\lambda,\mu}^{\star} T_{\lambda} = \phi_{\lambda,\mu}^{\star} \lie_{X_{\lambda}} T_{\lambda} + \phi_{\lambda,\mu}^{\star} \pd[T_{\lambda}]{\lambda}.
\]
\end{prop}

Note that in general, for one parameter families of vector fields, the pull back by the flow does not commute with the Lie derivative, i.e. 
\[
\phi_{\lambda,\mu}^{\star} \lie_{X_{\lambda}} T \ne \lie_{X_{\lambda}} \phi_{\lambda,\mu}^{\star} T.
\]
This is however true for vector fields
\[
\phi_{\lambda}^{\star} \lie_X T = \lie_X \phi_{\lambda}^{\star} T.
\]

The characterisation of the Lie derivative by the local flow implies that $\lie_X : \Omega^k \to \Omega^k$, i.e. $\lie_X$ maps $k$-forms to $k$-forms.  In this situation, we have the immensely useful Cartan magic formula.

\begin{prop}[Cartan Magic Formula]
The Lie derivative satisfies the relation
\[
\lie_X = d \circ \iota_X + \iota_X \circ d
\]
where $d$ is the exterior derivative and $\iota_X$ the insertion of $X$ into a $k$-form
\[
\iota_X \omega(X_1, \dotsc, X_{k-1}) = \omega(X, X_1, \dotsc, X_{k-1}).
\]
\end{prop}

Now we consider Riemannian manifolds as measure spaces, in particular so that we may integrate functions on $M$.

\begin{defn}
The metric induces a measure denoted $\measure_{\metric}$ given in local coordinates $\{x^i\}$ by
\[
\measure_{\metric} = \sqrt{\det \metric_{ij}} dx^1 \wedge \cdots \wedge dx^n.
\]
The measure $\measure_{\metric}$ is a volume form, i.e. $\measure_{\metric} \in \Lambda^n T^{\star}M$ is non-vanishing.
\end{defn}

An important application of the constructions above is the divergence of a vector field and the divergence theorem.

\begin{defn}
The divergence of a vector field $X$ with respect to the metric $\metric$ is defined by
\[
\div_{\metric} X = \trace (\conx X).
\]
\end{defn}

There is another notion of the divergence of a vector field.  If $\omega$ is a volume form then since it is everywhere non-vanishing, and $\Omega^n$ is a one-dimensional vector bundle, $\omega$ gives a global frame for $\Lambda^n T^{\star}M$.  Thus any section $\mu\in \Lambda^n T^{\star}M$ may be written $\mu = f \omega$ for some $f\in C^{\infty}(M)$.  In particular, $\lie_X \omega \in \Lambda^n T^{\star}M$ may be written in this form.

\begin{defn}
Let $\omega$ be a volume form.  The divergence of a vector field $X$ with respect to $\omega$ is defined by 
\[
(\div_{\omega} X) \omega = \lie_X \omega.
\]
\end{defn}

Note that by Cartan's magic formula we have $\lie_X \omega = (d \circ \iota_X + \iota_X \circ d) \omega = d \circ \iota_X \omega$.  Thus by Stokes' theorem we have the divergence theorem.

\begin{theorem}
Let $X$ be a vector field and $\omega$ a volume form on a Riemannian manifold $M$ with boundary.  Then
\[
\int_M \div_{\omega} X \omega = \int_{\bdry{M}} \iota_X \omega.
\]
\end{theorem}

When $\omega = \measure_{\metric}$ is the volume form induced by the metric, the two divergences defined above coincide.

\begin{prop}
Let $(M, \metric)$ be a Riemannian manifold, $\measure_{\metric}$ the induced measure and $X$ a vector field.  Then
\[
\div_{\metric} X = \div_{\measure_{\metric}} X.
\]
\end{prop}

We have the easily verified lemma.

\begin{lemma}
Let $(M,\metric)$ be a manifold with boundary $\bdry{M}$.  Let $\nor$ be the smooth outer unit normal vector field along $\bdry{M}$.  Let $\measure_{\metric}$ be the induced measure on $M$ and $\areameasure_{\metric}$ the induced measure on $\bdry{M}$ (induced by the pull back metric $i^{\star}\metric$ on $\bdry{M}$ by the inclusion $i: \bdry{M} \to M$).  Then for any vector field $X$ on $M$ we have
\[
\iota_X \measure = \metric(X, \nor) \areameasure.
\] 
\end{lemma}

This leads directly to the Riemannian divergence theorem.

\begin{theorem}
In the situation of the lemma we have
\[
\int_M \div X \measure_{\metric} = \int_{\bdry{M}} \metric(X, \nor) \areameasure_{\metric}.
\]
\end{theorem}

We record here a useful formula for the divergence.

\begin{lemma}
Let $f : M \to \RR$ be a smooth, positive function, $X$ a vector field and $\measure$ a volume form.  Then
\[
\div_{f\mu} (X) f\mu = \div_{\mu} (f X)\mu
\]
or equivalently
\[
\lie_X (f\mu) = \lie_{fX} \mu.
\]
\end{lemma}

\printbibliography
